### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by Bryan080204** [SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-Bryan080204#1]
Libreria _ Infografia
https://drive.google.com/file/d/1JJuKRLwo-2jbUeyTWO21MT2MbgeYpU_b/view?usp=sharing

**Comment by HECTOR-KDM02** [comment]
18 puntos

Mejorar el contenido solo poner partes mas importantes, verificar que tenga relaciones los temas que se abarcan, y verificar los gráficos ya que algunas no concuerdan con el contenido solicitado

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
